[package]
name = "tg-export"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.36", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.140"
stop-words = { version = "0.8.1", features = ["nltk"] }
thiserror = "2.0"
